### ISSUE TITLE
OperationalError: unrecognized token Errors with mysql2sqlite

### ISSUE THREAD

**Issue by tacitus5** [dumblob/mysql2sqlite#44]
Yesterday I tried to use mysql2sqlite.exe on a windows machine to migrate a dump from a rather big mysql-database to sqlite.

I made the mysql dump as suggested with

./mysqldump --skip-extended-insert --compact DB_name > dump_mysql.sql

(from windows powershell as administrator)

Of course I put in the correct database name for "DB_name". I got a file "dump_mysql.sql" that seemed to match the size of the database, but the sql was not readable by a text editor (only when changing to Hex view).

That notwithstanding I proceeded to your suggested conversion 

./mysql2sqlite dump_mysql.sql | ./sqlite3 mysqlite3.db

After about a minute I get multiple error messages 

> Error:
>  
>  incomplete SQL: Sqlite version :  3.8.7.4
> 
> 
> 6608_grenzw_ch
> insert or ignore into 6608_grenzw_ch (kurzzeit_ml, reference, gdate, kurzzeit_mg, bemerkung, cdate, > grenz_ml, pk, kurzzeit_t, chemid, grenz_mg) VALUES (NULL, NULL, NULL, NULL, '(einatembares Aerosol)', 2009-01-12, NULL, 3, '15', 6540, '0,01')
> Traceback (most recent call last):
> 
>   File "mysql2sqlite.py", line 330, in convert_mysql_to_sqlite
> 
> OperationalError: unrecognized token: "6608_grenzw_ch"
> 
> insert or ignore into 6608_grenzw_ch (kurzzeit_ml, reference, gdate, kurzzeit_mg, bemerkung, cdate, grenz_ml, pk, kurzzeit_t, chemid, grenz_mg) VALUES (NULL, NULL, NULL, NULL, NULL, 2008-02-08, '1', 6, '15', 8200, '3')
> Traceback (most recent call last):

and so on. 
Each error was seemingly located on line 330 of File 'mysql2sqlite.py" and each was about not recognizing the token "6608_grenzw_ch" which happens to be the name of one of the tables in the database.

Did I miss something important on my side? 
Or is the number of tables to convert from mysql to sqlite too large ?
(I have 128 tables in that database, all in utf-8 coding)
the table named 6608_grenzw_ch is OK on phpMyAdmin (checked status)
And the whole MySQL database DOES work on my localhost as expected.

Hope one of you can point out my mistake or offer advice how to do better ... 

or did I find a bug?

**Comment by dumblob** [comment]
Hi @tacitus5, thanks for the report.

First of all I'm slightly confused about the error messages you've showed as they say `File "mysql2sqlite.py", line 330, in convert_mysql_to_sqlite` which means some Python script (perhaps https://github.com/wanliyun/mysql2sqlite.py or https://github.com/bookmine/libgen-tools/blob/master/db-tools/mysql2sqlite.py or https://github.com/Averell7/mysql2sqlite or some other...) but this repository contains a script written in the POSIX programming language *AWK*.

Could you please make sure you're really using the AWK script from this repository?

However I can partially answer at least one of you questions already now :wink:. Namely whether the number of tables is too large for sqlite3 to handle and therefore also too large to convert.

The answer is very simply **no**. Your number of tables is really far from being too large for sqlite3 :smile: - see [sqlite3 limits](https://www.sqlite.org/limits.html ) (at the bottom is the table number limit).

The AWK script in this repository is a pure stream processor and therefore it's also nearly unlimited - the very single limit is the number of bytes on one line in the input SQL dump. This limit is equal to the limit of a *record* in the AWK implementation you're using (POSIX requires it to be at least [{LINE_MAX}](http://pubs.opengroup.org/onlinepubs/7908799/xsh/limits.h.html ) long, which is 2048, but the most widespread AWK implementations support a way higher number - see e.g. [gawk (GNU AWK)](https://www.gnu.org/software/gawk/manual/html_node/Implementation-Limitations.html) supporting *MAX_INT* bytes).

**Comment by tacitus5** [comment]
Hi dumblob,
first of all thanks for your comments. I didnt have the time to wait for your answer longer than 2 days, so I resorted to writing a php script doing the convering of mysql to sqlite - which finally works, albeit very slow, taking hours ...  - but no errors, no bugs, and the sqlite database is fully functional.

Since I have to do the same thing mre often I would realy appreciate a faster solution.

You may have missed the point that I am working (and really MUST BE) on a Windows 10 Machine, not on any linux or unix which brings awk with it. Windows doesn't know about AWK.

I used "mysql2sqlite.exe" 
downloaded from 
https://sourceforge.net/projects/mysql2sqlite/

which is said to be windows executable
"About the Windows executable and the Python script :
Usage : edit the in i file to fit your system, and just run the exe or the python script."

So this WINDOWS version uses python.

Is there a newer Windows version (the one from sourceforge is said to have last been updated 3 years ago) somewhere? 

Or alternatively - how can I use AWK on windows without using a virtual machine and all that Overhead?
